version: '3'
services: 
  # setup db container
  db:
    image: 'mongo'
    container_name: 'mongodb'
    ports: 
      - 127.0.0.1:27017:27017
  # setup node container
  server: 
    build: ./backend
    expose:
      - 8000
    environment:
      - MONGO_URL=mongodb://localhost:27017/todo
      - API_HOST="http://localhost:4000/"
      - APP_SERVER_PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/server
    restart: unless-stopped
    depends_on:
      - db
    command: node server.js
  # setup client container
  client:
    build: ./
    environment: 
      - VUE_APP_PORT=8080
    expose: 
      - 8080
    ports: 
      - 8080:8080
    volumes: 
      - ./src:/app/client/src
      - ./public:/app/client/public
    command: npm run serve